version: "3"
services:

  # Proxy service to be added
  readerservice:
    build:
      context: ./reader-service
      dockerfile: Dockerfile
    ports:
      - "7071:8080"
    depends_on:
      - scylladb1
      - scylladb2
      - scylladb3
    restart: always

  writerservice:
    build:
      context: ./writer-service
      dockerfile: Dockerfile
    ports:
      - "7072:8080"
    depends_on:
      - scylladb1
      - scylladb2
      - scylladb3
    restart: always

  # scylladb cluster
  scylladb1:
    image: scylladb/scylla
    restart: always
    volumes:
      - ./volumes/db/1:/var/lib/scylla
    ports:
      - "9042:9042"
    command: "--smp 1 --memory 512M"

  scylladb2:
    image: scylladb/scylla
    restart: always
    links:
     - scylladb1:seed
    volumes:
      - ./volumes/db/2:/var/lib/scylla
    ports:
      - "9142:9042"
    command: "--seeds scylladb3,scylladb2 --smp 1 --memory 512M"

  scylladb3:
    image: scylladb/scylla
    restart: always
    links:
     - scylladb1:seed
    volumes:
      - ./volumes/db/3:/var/lib/scylla
    ports:
      - "9242:9042"
    command: "--seeds scylladb1,scylladb2 --smp 1 --memory 512M"
